services:

    flowr_amulensync.listplugins_eventsubscriber:
        class: Flowr\AmulenSyncBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }


    flowr_amulensync.showmenu_eventsubscriber:
        class: Flowr\AmulenSyncBundle\Event\ShowMenuSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }

    flowr_amulensync.collectjobs_eventsubscriber:
        class: Flowr\AmulenSyncBundle\Event\CollectJobsSubscriber
        tags:
            - { name: kernel.event_subscriber }

    flowr_amulensync.repository.setting:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Flowr\AmulenSyncBundle\Entity\Setting

    flowr_amulensync.settings:
        class: Flowr\AmulenSyncBundle\Service\SettingService
        arguments: ['@flowr_amulensync.repository.setting']