services:

    flowr_amulensync.listplugins_eventsubscriber:
        class: Flowr\AmulenSyncBundle\Event\ListPluginsSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }


    flowr_amulensync.showmenu_eventsubscriber:
        class: Flowr\AmulenSyncBundle\Event\ShowMenuSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }